export default {
  // email: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
  email: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i,
  number: /[^0-9]/g,
  mobileNo: /^\d{10}?([0-9]{4})$/,
  taxGST: /\d{2}[A-Z]{5}\d{4}[A-Z]{1}[A-Z\d]{1}[Z]{1}[A-Z\d]{1}/,
  taxPAN: /[A-Z]{5}[0-9]{4}[A-Z]{1}/,
  panno: /^([A-Z]){5}([0-9]){4}([A-Z]){1}$/,
  int: /^[0-9]*/,
  dot_check: /^[0-9]*\.[0-9]*/,
  underscore: /_/g,
  empty: /^ *$/,
  // onlyString: /^[a-zA-Z]+$/,
  IFSCCode: /^[A-Z]{4}0[A-Z0-9]{6}$/,
  bankAccountNumber: /^\d{9,18}$/,
  base64String:
    /^([0-9a-zA-Z+/]{4})*(([0-9a-zA-Z+/]{2}==)|([0-9a-zA-Z+/]{3}=))?$/,
  string: /^[aA-zZ\s]+$/,
  onlyString: /[^a-zA-Z]/g,
};
